export const dummyGameNews = [
    {
        slug: "quetta-football-championship-2025",
        category: "sports",
        published_date: "2025-11-30 22:15:00",
        feature_status: "yes",
        thumbnail: "https://footballpakistan.com/wp-content/uploads/2015/08/Almira-Rafique.jpg",
        title:
            "کوئٹہ میں فٹبال چیمپئن شپ 2025 کا آغاز — نوجوان کھلاڑیوں کی شاندار کارکردگی",
        summary:
            "بلوچستان فٹبال ایسوسی ایشن کی جانب سے کوئٹہ میں منعقدہ چیمپئن شپ میں 16 ٹیموں نے حصہ لیا۔ افتتاحی میچ میں کوئٹہ اسٹارز نے مستونگ یونائیٹڈ کو 3-1 سے شکست دی۔",
        news_id: 101,
    },
    {
        slug: "pakistan-cricket-academy-training",
        category: "sports",
        published_date: "2025-11-29 18:42:00",
        feature_status: "no",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbvp2PXaNlnze4xXTXP4bb32ogCWUZyvn17w&s",
        title:
            "پاکستان کرکٹ اکیڈمی میں نوجوان کھلاڑیوں کے لیے خصوصی تربیتی کیمپ کا آغاز",
        summary:
            "نیشنل اسٹیڈیم کراچی میں ہونے والے تربیتی کیمپ میں کوچز کی نگرانی میں کھلاڑیوں کو بیٹنگ، بولنگ اور فیلڈنگ کے جدید اصولوں سے آگاہ کیا جا رہا ہے۔",
        news_id: 102,
    },
    {
        slug: "balochistan-women-cricket-tournament",
        category: "sports",
        published_date: "2025-11-27 20:00:00",
        feature_status: "yes",
        thumbnail: "https://behtareen.pk/wp-content/uploads/2017/06/Bonanza-Satrangi-Pakistan-Womens-Cricket-Team-ICC-WCC-2017-PCB-696x392.jpg",
        title:
            "بلوچستان ویمن کرکٹ ٹورنامنٹ کا انعقاد — خواتین کھلاڑیوں کی شاندار شرکت",
        summary:
            "کوئٹہ میں ہونے والے اس ٹورنامنٹ میں بلوچستان بھر سے 12 ٹیموں نے حصہ لیا۔ فائنل میچ کل کوئٹہ گراؤنڈ میں کھیلا جائے گا۔",
        news_id: 103,
    },
    {
        slug: "quetta-hockey-league-finals",
        category: "sports",
        published_date: "2025-11-25 17:12:00",
        feature_status: "no",
        thumbnail: "https://asiahockey.org/wp-content/uploads/2023/05/WhatsApp-Image-2023-05-16-at-8.53.19-PM-1.jpeg",
        title:
            "بلوچستان ہاکی لیگ کے فائنل میں کوئٹہ ایگلز نے فتح حاصل کر لی",
        summary:
            "کوئٹہ ایگلز نے دلچسپ مقابلے کے بعد گوادر ٹائیگرز کو 2-0 سے شکست دے کر ٹرافی اپنے نام کی۔",
        news_id: 104,
    },
];
// 🏠 HOME NEWS
export const dummyHomeNews = [
    {
        slug: "quetta-development-project-2025",
        category: "home",
        published_date: "2025-12-01 21:10:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad",
        title: "بلوچستان میں ترقیاتی منصوبوں پر تیزی سے کام جاری — وزیراعلیٰ کا بیان",
        summary: "وزیراعلیٰ بلوچستان نے کہا کہ صوبے بھر میں ترقیاتی منصوبے عوامی ضروریات کو مد نظر رکھتے ہوئے مکمل کیے جا رہے ہیں۔",
        news_id: 201,
    },
    {
        slug: "quetta-cleanliness-campaign",
        category: "home",
        published_date: "2025-12-01 18:45:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da",
        title: "کوئٹہ میں صفائی مہم کا آغاز — شہریوں سے تعاون کی اپیل",
        summary: "ایڈمنسٹریٹر میٹروپولیٹن کارپوریشن نے شہر بھر میں صفائی مہم کے پہلے مرحلے کا آغاز کر دیا۔",
        news_id: 202,
    },
    {
        slug: "balochistan-roads-upgrade",
        category: "home",
        published_date: "2025-12-01 15:10:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
        title: "بلوچستان میں سڑکوں کی تعمیر و مرمت کا کام جاری",
        summary: "محکمہ مواصلات نے کوئٹہ، خضدار اور لورالائی میں سڑکوں کی بحالی کے منصوبے شروع کیے ہیں۔",
        news_id: 203,
    },
    {
        slug: "quetta-water-supply-project",
        category: "home",
        published_date: "2025-12-01 10:35:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
        title: "کوئٹہ میں واٹر سپلائی منصوبہ 80 فیصد مکمل — عوام کو جلد ریلیف ملنے کا امکان",
        summary: "واسا حکام کے مطابق شہر کے مختلف علاقوں میں پانی کی فراہمی کے منصوبے تکمیل کے قریب ہیں۔",
        news_id: 204,
    },
];
// 🕓 LATEST NEWS
export const dummyLatestNews = [
    {
        slug: "balochistan-cabinet-meeting",
        category: "latest",
        published_date: "2025-12-01 20:05:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1581090700227-1e37b190418e",
        title: "بلوچستان کابینہ کا اجلاس — صوبائی بجٹ کی منظوری",
        summary: "اجلاس میں مختلف ترقیاتی اسکیموں کے لیے بجٹ کی منظوری دی گئی، وزیراعلیٰ نے شفافیت پر زور دیا۔",
        news_id: 301,
    },
    {
        slug: "gas-supply-resumed",
        category: "latest",
        published_date: "2025-12-01 18:40:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1576678927484-cc907957088c",
        title: "کوئٹہ میں گیس کی فراہمی بحال — عوام نے سکھ کا سانس لیا",
        summary: "سوئی سدرن گیس کمپنی کے مطابق مرمت مکمل ہونے کے بعد شہر بھر میں گیس بحال کر دی گئی۔",
        news_id: 302,
    },
    {
        slug: "balochistan-education-funds",
        category: "latest",
        published_date: "2025-12-01 17:00:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
        title: "بلوچستان میں تعلیمی اداروں کے لیے فنڈز میں اضافہ",
        summary: "محکمہ تعلیم نے سرکاری اسکولوں میں سہولیات کی بہتری کے لیے 2 ارب روپے مختص کیے۔",
        news_id: 303,
    },
    {
        slug: "quetta-weather-update",
        category: "latest",
        published_date: "2025-12-01 08:50:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1475694867812-f82b8696d610",
        title: "کوئٹہ میں موسم سرد — درجہ حرارت نقطہ انجماد سے نیچے",
        summary: "شہر میں درجہ حرارت منفی 2 ڈگری سینٹی گریڈ تک گر گیا، شہریوں نے گرم کپڑوں کا استعمال بڑھا دیا۔",
        news_id: 304,
    },
];
// 🎓 EDUCATION
export const dummyEducationNews = [
    {
        slug: "balochistan-scholarship-announcement",
        category: "education",
        published_date: "2025-12-01 19:15:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
        title: "بلوچستان حکومت کا طلبہ کے لیے اسکالرشپ پروگرام کا اعلان",
        summary: "وزیر تعلیم نے صوبے کے مستحق طلبہ کے لیے اسکالرشپ کی نئی اسکیم کا اعلان کیا۔",
        news_id: 401,
    },
    {
        slug: "teachers-training-session",
        category: "education",
        published_date: "2025-12-01 16:45:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b",
        title: "اساتذہ کے لیے تربیتی ورکشاپ — جدید تدریسی طریقوں پر توجہ",
        summary: "کوئٹہ میں ہونے والی ورکشاپ میں مختلف اسکولوں کے اساتذہ نے شرکت کی۔",
        news_id: 402,
    },
    {
        slug: "school-renovation-project",
        category: "education",
        published_date: "2025-12-01 14:20:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1588072432836-e10032774350",
        title: "بلوچستان میں اسکولوں کی تزئین و آرائش کا منصوبہ شروع",
        summary: "محکمہ تعلیم نے صوبے بھر کے اسکولوں میں سہولیات کی فراہمی کے لیے اقدامات شروع کر دیے۔",
        news_id: 403,
    },
    {
        slug: "university-research-grants",
        category: "education",
        published_date: "2025-12-01 09:55:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1523580494863-6f3031224c94",
        title: "بلوچستان یونیورسٹی میں ریسرچ گرانٹس کے لیے نئی پالیسی متعارف",
        summary: "جامعہ بلوچستان نے تحقیقی منصوبوں کے لیے طلبہ کو خصوصی گرانٹس دینے کا اعلان کیا۔",
        news_id: 404,
    },
];
// 💼 BUSINESS
export const dummyBusinessNews = [
    {
        slug: "balochistan-mineral-project",
        category: "business",
        published_date: "2025-12-01 19:00:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1581090469604-7b6f86a4c3ef",
        title: "بلوچستان میں معدنیات کے نئے منصوبوں پر سرمایہ کاری میں اضافہ",
        summary: "غیر ملکی کمپنیوں نے بلوچستان کے مختلف معدنیاتی علاقوں میں دلچسپی کا اظہار کیا۔",
        news_id: 501,
    },
    {
        slug: "gwadar-port-trade",
        category: "business",
        published_date: "2025-12-01 16:30:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1601047497320-3b4d1bb1da3b",
        title: "گوادر پورٹ پر تجارتی سرگرمیوں میں 20 فیصد اضافہ",
        summary: "گوادر بندرگاہ پر رواں ماہ کے دوران برآمدات میں نمایاں اضافہ ریکارڈ کیا گیا۔",
        news_id: 502,
    },
    {
        slug: "local-handicrafts-export",
        category: "business",
        published_date: "2025-12-01 13:15:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1578574577315-3fbeb0cecdc2",
        title: "بلوچستان کی دستکاری مصنوعات کو عالمی سطح پر پذیرائی ملنے لگی",
        summary: "مقامی کاریگروں کی مصنوعات کو مشرق وسطیٰ اور یورپ میں فروخت کے نئے مواقع ملے۔",
        news_id: 503,
    },
    {
        slug: "small-industries-support",
        category: "business",
        published_date: "2025-12-01 08:10:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1581093588401-22c9b6bff1c5",
        title: "چھوٹی صنعتوں کے فروغ کے لیے خصوصی پیکیج کا اعلان",
        summary: "حکومت نے بلوچستان میں چھوٹے کاروباروں کو مراعات دینے کا فیصلہ کیا ہے۔",
        news_id: 504,
    },
];
// ❤️ HEALTH
export const dummyHealthNews = [
    {
        slug: "balochistan-healthcare-centers",
        category: "health",
        published_date: "2025-12-01 18:40:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1588776814546-2e6a40b5c7e3",
        title: "بلوچستان میں صحت کے مراکز کی بحالی — نئے ڈاکٹروں کی تعیناتی",
        summary: "محکمہ صحت نے صوبے بھر میں صحت کے مراکز میں 300 نئے ڈاکٹروں کی بھرتی کا اعلان کیا۔",
        news_id: 601,
    },
    {
        slug: "vaccination-campaign-quetta",
        category: "health",
        published_date: "2025-12-01 15:20:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1582719478181-2a9b0b1c59b4",
        title: "کوئٹہ میں حفاظتی ٹیکوں کی مہم کا آغاز",
        summary: "محکمہ صحت کے مطابق اس مہم کے دوران 2 لاکھ بچوں کو ویکسین دی جائے گی۔",
        news_id: 602,
    },
    {
        slug: "mental-health-awareness",
        category: "health",
        published_date: "2025-12-01 12:00:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1576765607924-3f7b18d3e06c",
        title: "بلوچستان میں ذہنی صحت کے حوالے سے آگاہی مہم کا آغاز",
        summary: "سرکاری اور غیر سرکاری تنظیموں کے تعاون سے صوبے بھر میں آگاہی سیشنز منعقد کیے جا رہے ہیں۔",
        news_id: 603,
    },
    {
        slug: "hospital-upgrade-project",
        category: "health",
        published_date: "2025-12-01 09:10:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144",
        title: "بلوچستان کے سرکاری اسپتالوں میں جدید مشینری کی تنصیب",
        summary: "محکمہ صحت نے اعلان کیا ہے کہ تمام ضلعی اسپتالوں میں MRI اور CT اسکین کی سہولت فراہم کی جائے گی۔",
        news_id: 604,
    },
];
// ✍️ LITRATURE
export const dummyLitratureNews = [
    {
        slug: "baloch-poetry-event",
        category: "litrature",
        published_date: "2025-12-01 18:00:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1528740561666-dc2479dc08ab",
        title: "بلوچ ادبی میلے کا انعقاد — شعرا کی شاندار شرکت",
        summary: "ادبی میلے میں نوجوان شعرا نے جدید اور کلاسیکی شاعری کے امتزاج سے حاضرین کو محظوظ کیا۔",
        news_id: 701,
    },
    {
        slug: "book-launch-quetta",
        category: "litrature",
        published_date: "2025-12-01 15:00:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
        title: "کوئٹہ میں مقامی مصنف کی نئی کتاب کی رونمائی",
        summary: "کتاب کا عنوان ’بلوچ ثقافت کی روح‘ ہے، جس میں بلوچستان کی ادبی تاریخ پر روشنی ڈالی گئی ہے۔",
        news_id: 702,
    },
    {
        slug: "urdu-literature-festival",
        category: "litrature",
        published_date: "2025-12-01 12:45:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1526318472351-bc6e6c8c0c74",
        title: "اردو ادب فیسٹیول 2025 — نوجوان ادیبوں کی بڑی شرکت",
        summary: "تقریب میں 40 سے زائد مصنفین اور ادیبوں نے شرکت کی۔",
        news_id: 703,
    },
    {
        slug: "art-and-culture-night",
        category: "litrature",
        published_date: "2025-12-01 10:25:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1533750349088-cd871a92f312",
        title: "بلوچ ثقافت اور ادب کی رات — فنکاروں نے داد سمیٹی",
        summary: "ادبی محفل میں موسیقی اور شاعری کا حسین امتزاج دیکھنے کو ملا۔",
        news_id: 704,
    },
];
// 🔬 SCIENCE & TECHNOLOGY
export const dummyScienceAndTechnologyNews = [
    {
        slug: "balochistan-tech-incubator",
        category: "science_and_technology",
        published_date: "2025-12-01 17:50:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
        title: "بلوچستان میں ٹیکنالوجی انکیوبیٹر سینٹر کا قیام",
        summary: "محکمہ آئی ٹی نے نوجوان اسٹارٹ اپس کے لیے جدید سہولیات سے آراستہ مرکز قائم کیا۔",
        news_id: 801,
    },
    {
        slug: "students-robotics-competition",
        category: "science_and_technology",
        published_date: "2025-12-01 15:40:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1603791452906-bc3ba7eaed1d",
        title: "بلوچستان یونیورسٹی میں روبوٹکس مقابلے کا انعقاد",
        summary: "طلبہ نے مختلف خودکار روبوٹس تیار کر کے اپنی صلاحیتوں کا مظاہرہ کیا۔",
        news_id: 802,
    },
    {
        slug: "digital-training-program",
        category: "science_and_technology",
        published_date: "2025-12-01 13:30:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1581090700227-1e37b190418e",
        title: "کوئٹہ میں ڈیجیٹل ہنر مندی پروگرام شروع",
        summary: "محکمہ آئی ٹی نے نوجوانوں کو جدید ٹیکنالوجی سے متعارف کرانے کے لیے پروگرام شروع کیا۔",
        news_id: 803,
    },
    {
        slug: "ai-awareness-campaign",
        category: "science_and_technology",
        published_date: "2025-12-01 09:20:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f",
        title: "بلوچستان میں مصنوعی ذہانت سے متعلق آگاہی مہم کا آغاز",
        summary: "یونیورسٹی آف بلوچستان میں طلبہ کے لیے AI ورکشاپس کا انعقاد کیا گیا۔",
        news_id: 804,
    },
];
// 🎭 CULTURE
export const dummyCultureNews = [
    {
        slug: "baloch-cultural-festival-quetta",
        category: "culture",
        published_date: "2025-12-01 19:05:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1556745757-8d76bdb6984b",
        title: "بلوچ ثقافتی میلہ — موسیقی، رقص اور روایتی کھانوں کی بہار",
        summary: "کوئٹہ میں منعقدہ ثقافتی میلے میں ہزاروں افراد نے شرکت کی۔",
        news_id: 901,
    },
    {
        slug: "heritage-site-restoration",
        category: "culture",
        published_date: "2025-12-01 16:10:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
        title: "بلوچستان کے تاریخی مقامات کی بحالی پر کام جاری",
        summary: "محکمہ آثار قدیمہ نے خضدار اور مکران کے تاریخی مقامات پر بحالی منصوبے شروع کیے۔",
        news_id: 902,
    },
    {
        slug: "traditional-art-exhibition",
        category: "culture",
        published_date: "2025-12-01 12:55:00",
        feature_status: "no",
        thumbnail: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6",
        title: "بلوچ روایتی آرٹ کی نمائش — نوجوان فنکاروں کی پذیرائی",
        summary: "نمائش میں بلوچستان کے مختلف علاقوں کے فنکاروں نے اپنے شاہکار پیش کیے۔",
        news_id: 903,
    },
    {
        slug: "folk-music-night",
        category: "culture",
        published_date: "2025-12-01 09:30:00",
        feature_status: "yes",
        thumbnail: "https://images.unsplash.com/photo-1523757956233-94a86ff74ea5",
        title: "بلوچ لوک موسیقی کی شام — سامعین جھوم اٹھے",
        summary: "لوک گلوکاروں کی شاندار پرفارمنس نے حاضرین کو محظوظ کر دیا۔",
        news_id: 904,
    },
];
// 📰 COLUMN NEWS
export const dummyColumnNews = [
  {
    slug: "balochistan-political-analysis-2025",
    category: "column",
    published_date: "2025-12-01 20:30:00",
    feature_status: "yes",
    thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
    title: "بلوچستان کی سیاست — نئے دور کی شروعات یا پرانے مسائل؟",
    summary: "کالم نگار نے بلوچستان کی موجودہ سیاسی صورتحال کا تفصیلی تجزیہ پیش کیا ہے اور ممکنہ تبدیلیوں پر روشنی ڈالی ہے۔",
    news_id: 1001,
  },
  {
    slug: "education-reform-opinion",
    category: "column",
    published_date: "2025-12-01 17:45:00",
    feature_status: "no",
    thumbnail: "https://images.unsplash.com/photo-1588072432836-e10032774350",
    title: "تعلیمی نظام میں اصلاحات — ایک ناگزیر ضرورت",
    summary: "کالم میں مصنف نے صوبے کے تعلیمی نظام میں درپیش چیلنجز اور ان کے حل پر روشنی ڈالی ہے۔",
    news_id: 1002,
  },
  {
    slug: "economic-conditions-commentary",
    category: "column",
    published_date: "2025-12-01 15:20:00",
    feature_status: "no",
    thumbnail: "https://images.unsplash.com/photo-1581090469604-7b6f86a4c3ef",
    title: "بلوچستان کی معیشت — مواقع اور مشکلات",
    summary: "کالم نگار کے مطابق بلوچستان میں قدرتی وسائل کے باوجود معیشت کے مسائل بدستور برقرار ہیں۔",
    news_id: 1003,
  },
  {
    slug: "social-change-and-youth",
    category: "column",
    published_date: "2025-12-01 10:05:00",
    feature_status: "yes",
    thumbnail: "https://images.unsplash.com/photo-1520975918318-3e5b29b6ef97",
    title: "نوجوان اور سماجی تبدیلی — امید کی ایک نئی کرن",
    summary: "کالم میں نوجوان نسل کے کردار پر زور دیا گیا ہے جو بلوچستان کی سماجی ترقی میں بنیادی حیثیت رکھتی ہے۔",
    news_id: 1004,
  },
];
